title: >
  LivePublication
subtitle: > 
  The science workflow creates and updates the publication
date: 2023-07-04
date-format: short
abstract: >
  The uptake of computational methods to support research has 
  led to some remarkable new tools and methods to improve outcomes. 
  But one unintended consequence is that the scientific record ends 
  up being fragmented and distributed amongst several distinct systems.  
  The research we report aims to gather together \textit{all} of the 
  components of an experiment into a single container---including the 
  publication itself.  We describe the architecture of such a system 
  that marries together distributed workflows (Globus) with research 
  object containers (RO-Crate) and adds new methods to describe, 
  update and `publish' the details of the workflow and its outcomes. 
  Finally, we demonstrate the system with a natural language processing 
  research use case.
keywords:
  - Computational Science
  - Publication
  - Reproducibility
  - Workflows
title-block-banner: true
title-block-style: default
bibliography: references.bib
csl: acm-sig-proceedings.csl
execute:
  echo: false
format:
  html:
    code-fold: true
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
filters:
  - add-code-files
  - social-share
  - shinylive
jupyter: python3
share:
  permalink: "https://mr.schochastics.net/"
  description: "awesome page"
  twitter: true
  facebook: true
  reddit: true
  linkedin: true
  email: true
authors:
  - name: Augustus Ellerm
    affiliations:
      - ref: uc
    corresponding: true
    email: gus.ellerm@pg.canterbury.ac.nz
    orcid: 0000-0001-8260-231X
    equal-contributor: true
  - name: Mark Gahegan
    affiliations:
      - ref: ua
    orcid: 0000-0001-7209-8156
  - name: Benjamin Adams
    affiliations:
      - ref: uc
    orcid: 0000-0002-1657-9809
affiliations:
  - id: uc
    name: University of Canterbury, Christchurch, New Zealand
  - id: ua
    name: University of Auckland, Auckland, New Zealand
toc: true
toc-depth: 2
css: styles.css